##  Standard Scaler

In [1]:
import numpy as np
import pandas as pd
import matplotlib as plt

In [2]:
df=pd.read_csv("/kaggle/input/datasets/nikhil7280/student-performance-multiple-linear-regression/Student_Performance.csv")
df

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,Yes,9,1,91.0
1,4,82,No,4,2,65.0
2,8,51,Yes,7,2,45.0
3,5,52,Yes,5,2,36.0
4,7,75,No,8,5,66.0
...,...,...,...,...,...,...
9995,1,49,Yes,4,2,23.0
9996,7,64,Yes,8,5,58.0
9997,6,83,Yes,8,5,74.0
9998,9,97,Yes,7,0,95.0
9999,7,74,No,8,1,64.0

In [3]:
df=df.drop("Extracurricular Activities",axis=1)
df

,Hours Studied,Previous Scores,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,9,1,91.0
1,4,82,4,2,65.0
2,8,51,7,2,45.0
3,5,52,5,2,36.0
4,7,75,8,5,66.0
...,...,...,...,...,...
9995,1,49,4,2,23.0
9996,7,64,8,5,58.0
9997,6,83,8,5,74.0
9998,9,97,7,0,95.0
9999,7,74,8,1,64.0

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
X_train,X_test,y_train,y_test=train_test_split(df.drop("Performance Index",axis=1),
                                                df["Performance Index"],
                                                 test_size=0.2,
                                                 random_state=0)

In [6]:
from sklearn.preprocessing import StandardScaler
Scaler=StandardScaler()
X_train_scaled=Scaler.fit_transform(X_train)
X_test_scaled=Scaler.transform(X_test)

In [7]:
X_train_scaled

array([[ 0.01177784,  1.46795645, -0.31740964, -0.20579059],
       [-1.14669864,  1.63989277,  0.2720233 , -0.20579059],
       [-1.14669864, -0.25140672,  0.86145625, -1.25196174],
       ...,
       [-1.53285746,  0.37902645, -0.31740964,  0.14293313],
       [-0.37438098, -1.45496093, -1.49627552,  1.18910429],
       [ 1.17025433,  0.78021119,  0.86145625, -1.25196174]])

In [8]:
X_test_scaled

array([[-0.37438098, -0.1367825 ,  1.45088919, -0.5545143 ],
       [ 1.17025433, -0.53796724, -1.49627552,  0.84038057],
       [ 0.39793667,  1.18139592, -0.90684258,  0.49165685],
       ...,
       [-1.14669864,  0.9521475 ,  0.2720233 ,  0.84038057],
       [-0.37438098, -1.51227304,  0.86145625,  0.14293313],
       [-0.76053981, -1.62689725, -0.90684258, -1.25196174]])

In [9]:
X_train_scaled = pd.DataFrame(X_train_scaled, columns=X_train.columns)
X_test_scaled = pd.DataFrame(X_test_scaled, columns=X_test.columns)

In [10]:
X_train_scaled

,Hours Studied,Previous Scores,Sleep Hours,Sample Question Papers Practiced
0,0.011778,1.467956,-0.317410,-0.205791
1,-1.146699,1.639893,0.272023,-0.205791
2,-1.146699,-0.251407,0.861456,-1.251962
3,-1.146699,-1.512273,0.861456,0.491657
4,-1.532857,0.952148,-0.906843,1.537828
...,...,...,...,...
7995,0.011778,-0.308719,-1.496276,-0.554514
7996,0.397937,0.493651,1.450889,0.491657
7997,-1.532857,0.379026,-0.317410,0.142933
7998,-0.374381,-1.454961,-1.496276,1.189104
7999,1.170254,0.780211,0.861456,-1.251962

In [11]:
np.round(X_train.describe(), 1)

,Hours Studied,Previous Scores,Sleep Hours,Sample Question Papers Practiced
count,8000.0,8000.0,8000.0,8000.0
mean,5.0,69.4,6.5,4.6
std,2.6,17.4,1.7,2.9
min,1.0,40.0,4.0,0.0
25%,3.0,54.0,5.0,2.0
50%,5.0,69.0,7.0,5.0
75%,7.0,85.0,8.0,7.0
max,9.0,99.0,9.0,9.0

In [12]:
np.round(X_train_scaled.describe(), 1)

,Hours Studied,Previous Scores,Sleep Hours,Sample Question Papers Practiced
count,8000.0,8000.0,8000.0,8000.0
mean,0.0,0.0,-0.0,0.0
std,1.0,1.0,1.0,1.0
min,-1.5,-1.7,-1.5,-1.6
25%,-0.8,-0.9,-0.9,-0.9
50%,0.0,-0.0,0.3,0.1
75%,0.8,0.9,0.9,0.8
max,1.6,1.7,1.5,1.5