## MinMax Scaler

In [1]:
import numpy as np
import pandas as pd
import matplotlib as plt
import seaborn as sns

In [2]:
df=pd.read_csv("/kaggle/input/datasets/nikhil7280/student-performance-multiple-linear-regression/Student_Performance.csv")
df

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,Yes,9,1,91.0
1,4,82,No,4,2,65.0
2,8,51,Yes,7,2,45.0
3,5,52,Yes,5,2,36.0
4,7,75,No,8,5,66.0
...,...,...,...,...,...,...
9995,1,49,Yes,4,2,23.0
9996,7,64,Yes,8,5,58.0
9997,6,83,Yes,8,5,74.0
9998,9,97,Yes,7,0,95.0
9999,7,74,No,8,1,64.0

In [3]:
df=df.drop("Extracurricular Activities",axis=1)

In [4]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.drop("Performance Index",axis=1),
                                                        df["Performance Index"],
                                                          test_size=0.2,
                                                          random_state=0)

In [5]:
from sklearn.preprocessing import MinMaxScaler
Scaler=MinMaxScaler()
X_train_scaled=Scaler.fit_transform(X_train)
X_test_scaled=Scaler.transform(X_test)

In [6]:
X_train

,Hours Studied,Previous Scores,Sleep Hours,Sample Question Papers Practiced
7389,5,95,6,4
9275,2,98,7,4
2995,2,65,8,1
5316,2,43,8,6
356,1,86,5,9
...,...,...,...,...
9225,5,64,4,3
4859,6,78,9,6
3264,1,76,6,5
9845,4,44,4,8
2732,8,83,8,1

In [7]:
X_train_scaled = pd.DataFrame(X_train_scaled, columns=X_train.columns)
X_test_scaled = pd.DataFrame(X_test_scaled, columns=X_test.columns)

In [8]:
X_train_scaled

,Hours Studied,Previous Scores,Sleep Hours,Sample Question Papers Practiced
0,0.500,0.932203,0.4,0.444444
1,0.125,0.983051,0.6,0.444444
2,0.125,0.423729,0.8,0.111111
3,0.125,0.050847,0.8,0.666667
4,0.000,0.779661,0.2,1.000000
...,...,...,...,...
7995,0.500,0.406780,0.0,0.333333
7996,0.625,0.644068,1.0,0.666667
7997,0.000,0.610169,0.4,0.555556
7998,0.375,0.067797,0.0,0.888889
7999,0.875,0.728814,0.8,0.111111