### Import Libraries

In [1]:
import pandas as pd
import matplotlib.pyplot as plt

### Load DataSet

In [43]:
df=pd.read_csv("/kaggle/input/datasets/nikhil7280/student-performance-multiple-linear-regression/Student_Performance.csv")
df

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,Yes,9,1,91.0
1,4,82,No,4,2,65.0
2,8,51,Yes,7,2,45.0
3,5,52,Yes,5,2,36.0
4,7,75,No,8,5,66.0
...,...,...,...,...,...,...
9995,1,49,Yes,4,2,23.0
9996,7,64,Yes,8,5,58.0
9997,6,83,Yes,8,5,74.0
9998,9,97,Yes,7,0,95.0
9999,7,74,No,8,1,64.0

### Convert Extracurricular Activities column value into Zeroes and One
     ONE HOT Encoding

In [44]:
df = pd.get_dummies(df, columns=["Extracurricular Activities"], drop_first=True,dtype=int)

In [45]:
df

,Hours Studied,Previous Scores,Sleep Hours,Sample Question Papers Practiced,Performance Index,Extracurricular Activities_Yes
0,7,99,9,1,91.0,1
1,4,82,4,2,65.0,0
2,8,51,7,2,45.0,1
3,5,52,5,2,36.0,1
4,7,75,8,5,66.0,0
...,...,...,...,...,...,...
9995,1,49,4,2,23.0,1
9996,7,64,8,5,58.0,1
9997,6,83,8,5,74.0,1
9998,9,97,7,0,95.0,1
9999,7,74,8,1,64.0,0

In [49]:
X=df.drop(["Performance Index"],axis=1)
X

,Hours Studied,Previous Scores,Sleep Hours,Sample Question Papers Practiced,Extracurricular Activities_Yes
0,7,99,9,1,1
1,4,82,4,2,0
2,8,51,7,2,1
3,5,52,5,2,1
4,7,75,8,5,0
...,...,...,...,...,...
9995,1,49,4,2,1
9996,7,64,8,5,1
9997,6,83,8,5,1
9998,9,97,7,0,1
9999,7,74,8,1,0

In [50]:
y=df['Performance Index']
y

0       91.0
1       65.0
2       45.0
3       36.0
4       66.0
        ...
9995    23.0
9996    58.0
9997    74.0
9998    95.0
9999    64.0
Name: Performance Index, Length: 10000, dtype: float64

### Split dataset

In [52]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=2)

### Normalized Data

In [53]:
from sklearn.preprocessing import StandardScaler

In [59]:
Scaled=StandardScaler()
X_train=Scaled.fit_transform(X_train)
X_test=Scaled.transform(X_test)

### Train Model

In [61]:
from sklearn.linear_model import LinearRegression

In [62]:
lr=LinearRegression()

In [63]:
lr.fit(X_train,y_train)

LinearRegression()

### Predict

In [64]:
y_pred=lr.predict(X_test)

### Calculate R2 Score

In [65]:
from sklearn.metrics import r2_score

In [66]:
r2_score(y_pred,y_test)

0.9890849512748068